const Texts = {
  Log_In: 'Log In',
  Lets_meet: 'Let’s meeting new',
  People_aound: 'people around you',
  Login_With_phone: 'Login with Phone',
  Login_with_Google: 'Login with Google',
  Dont_have_account: `Don't have an account?`,
  Sign_Up: 'Sign Up',
  Sign_In: 'Sign In',
  Sign_up_with_Google: 'Sign up with Google',
  Sign_up_with_phone_number: 'Sign up with phone number',
  Create_account_now: 'Create account now',
  By_creating: 'By creating account, you agree to our',
  Terms: 'Terms',
  Learn: 'Learn',
  how_process_your_our: 'how we process your data in our ',
  Privacy_Policy: 'Privacy Policy',
  and: 'and',
  Cookie_Policy: 'Cookie Policy.',
  Enter_OTP: 'Enter OTP',
  We_sent_OTP_email: `We’ve sent an OTP code to your email`,
  Didnt_receive_code: `Didn’t receive any code? `,
  Resend: 'Resend',
  Verify: 'Verify',
  Remembered_Password: 'Remembered Password?',
  Take_selfie_photo: 'Take selfie photo',
  Your_face_must_be_clearly_visible: 'Your face must be clearly visible',
  Skip_for_now: 'Skip for now',
  Fill_your_details: 'Fill in your details',
  Please_ensure_that:
    'Please ensure that all the details you provide match your national identification. Any discrepancies may result in legal consequences and police action.',
  Continue: 'Continue',
  Name: 'Name',
  Age: 'Age',
  Location: 'Location',
  Email_Address: 'Email Address',
  Contact_Number: 'Contact Number',
  Palls_Date: 'Palls Date',
  Palls_Buddy: 'Palls Buddy',
  Enter_Number: 'Please enter your phone number',
  Phone_Number: 'Phone Number',
  Next: 'Next',
  Gender: 'What’s your gender?',
  Women: 'Women',
  Men: 'Men',
  Recent_pic: 'Add your recent pics',
  Upload_Photo:
    'Upload 2 photos to start. Add 4 or more to make your profile stand out.',
  What_Looking: 'What are you looking for right now?',
  Long_partner: 'Long-term partner',
  Open_Short: 'Long-term, open to short',
  Open_Long: 'Short-term, open to long',
  New_Friends: 'New friends',
  Still_Figuring: 'Still figuring it out',
  Interesting_About_You: 'Add something interesting about you',
  Interesting_Fact: 'Write interesting facts about yourself',
  Everyne_Know:
    'Let everyone know what you’re passionate about, by adding it to your profile.',
  Entertainment_Leisure: 'Entertainment & Leisure',
  Outdoor_Adventure: 'Outdoor & Adventure',
  Food_Experiences: 'Food & Drink Experiences',
  Learning_Creativity: 'Learning & Creativity',
  Explore_Buddies: 'Explore buddies!',
  Connect_Friends:
    'Connect with friends who share your favourite activities or interests.',
  Explore_buddies: 'Explore buddies',
  Retake: 'Retake',
  Submit: 'Submit',
  Instrumental_Musical :'Instrumental Musical is an intimate event for those who love instrumental melodies to soothe their feelings.'
};
export default Texts;
